---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	retrieve(retrieve)
	knowledge(knowledge)
	llm_decide(llm_decide)
	error_reply(error_reply)
	alert(alert)
	doc(doc)
	__end__([<p>__end__</p>]):::last
	__start__ --> retrieve;
	alert --> doc;
	doc --> error_reply;
	retrieve -. &nbsp;error&nbsp; .-> alert;
	retrieve -. &nbsp;าตฮ๑&nbsp; .-> knowledge;
	retrieve -. &nbsp;normal&nbsp; .-> llm_decide;
	error_reply --> __end__;
	knowledge --> __end__;
	llm_decide --> __end__;
%%	classDef default fill:#f2f0ff,line-height:1.2
%%	classDef first fill-opacity:0
%%	classDef last fill:#bfb6fc
